# Calculate the total revenue generated by two product categories in a store

import numpy as np

cat1_revenue = np.array([500, 600, 700, 550])

category2_revenue = np.array([450, 700, 800, 600])

print("Total revenue : ", cat1_revenue+category2_revenue)

# my_string = "Hello, World!"
# print(my_string.split())